#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

mkdir -p constant/triSurface

cp -f \
    ./Geometry/rudder.stl \
    constant/triSurface/
    
runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication decomposePar

mpirun -np 8 snappyHexMesh  -parallel -dict ./system/snappyHexMeshDict -overwrite

runParallel redistributePar -reconstruct -constant -overwrite

touch ca.foam

#runApplication decomposePar

#runParallel snappyHexMesh -overwrite

#runParallel redistributePar -reconstruct -constant -overwrite

runApplication renumberMesh -constant -overwrite

checkMesh
#------------------------------------------------------------------------------
